name: Continuous Integration

on:
  push:
    branches:
      - master

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    env:
      TEST_VAR: ${{ secrets.TEST_VAR }}
    steps:
    - run: echo $TEST_VAR