name: Check pull requests are valid

on:
  pull_request:
    types:
    - opened
    - labeled
    - unlabeled
    - synchronize

jobs:
  check-rules:
    runs-on: ubuntu-latest

    steps:
    - name: Release cannot be source branch
      if: ${{ github.head_ref == 'release' }}
      run: exit error

    - name: Master can only merge to release
      if: ${{ github.head_ref == 'master' && github.base_ref != 'release' }}
      run: exit error

    - name: Release must have a version label
      if: ${{ github.base_ref == 'release' }}
      uses: mheap/github-action-required-labels@v1
      with:
        mode: exactly
        count: 1
        labels: major, minor, patch

    - name: Pull requests must link an issue
      if: contains(github.event.pull_request.labels.*.name, 'dependencies') == false
      uses: hattan/verify-linked-issue-action@v1.1.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Release must have Release in title
      if: ${{ github.base_ref == 'release' }}
      uses: deepakputhraya/action-pr-title@master
      with:
        allowed_prefixes: 'Release'
        prefix_case_sensitive: true
